openapi jaxb 2.0
icellmobilsoft/openapi-jaxb pull request #19
Opened 2023-01-11 14:18 UTC by petrenyi-mark

closes #18 

* remove swagger-jaxb dependencies
* refactor processing to primary work with Outlines
* jaxb 2.3 -> 4.0
* microprofile-openapi 1.0 -> 2.0
* replace demo project with unit tests
* introduce icellmobilsoft oss parent pom
* add default github actions

2023-01-11 14:42 UTC, rombow approved these changes, later dismissed

2023-01-11 14:42 UTC, rombow commented on README.adoc
> +        <version>2.0.0</version>
Ne egessuk bele a verzioszamot, kifelejtjuk frissiteni

2023-01-11 14:42 UTC, rombow commented on docs/index.adoc
> +        <version>2.0.0</version>
itt is valami utalast csak a verzioszamra kellene

2023-01-11 14:42 UTC, rombow commented on openapi-jaxb-plugin/pom.xml
> +        <microprofile-openapi-api.version>2.0.1</microprofile-openapi-api.version>
Doksiban 3.0.0 van irva

2023-01-11 14:53 UTC, speter555 commented on .github/workflows/compile_maven.yml
> +name: Compile with Maven
https://github.com/i-Cell-Mobilsoft-Open-Source/parent-pom/blob/master/.github/workflows/compile.yml copy paste lehetne

2023-01-11 14:58 UTC, rombow approved these changes, later dismissed

2023-01-11 15:12 UTC, speter555 approved these changes, later dismissed

2023-01-11 15:12 UTC, speter555 commented on .github/workflows/docs.yml
> +jobs:
copy paste https://github.com/i-Cell-Mobilsoft-Open-Source/parent-pom/blob/master/.github/workflows/docs.yml

2023-01-11 15:36 UTC, bucherarnold approved these changes, later dismissed

2023-01-11 15:55 UTC, czenczl approved these changes, later dismissed

2023-01-12 12:58 UTC, czenczl submitted a review, later dismissed

2023-01-12 13:05 UTC, speter555 approved these changes, later dismissed

2023-01-12 13:07 UTC, bucherarnold submitted a review, later dismissed

2023-01-12 13:27 UTC, rombow requested changes, later dismissed

2023-01-12 13:27 UTC, rombow commented on .github/workflows/manual_release.yml
> +        uses: actions/setup-java@v1
ez tuti regi

2023-01-12 13:44 UTC, petrenyi-mark commented on .github/workflows/manual_release.yml
> +        uses: actions/setup-java@v1
jogos ez kimaradt - frissítettem

2023-01-12 13:58 UTC, rombow requested changes

2023-01-12 13:58 UTC, rombow commented on .github/workflows/manual_release.yml
> +        uses: actions/setup-java@v1
meg mindig a regi workflow latszodik

2023-01-12 15:23 UTC, rombow approved these changes

2023-01-12 15:49 UTC, czenczl approved these changes

2023-01-12 20:19 UTC, speter555 approved these changes

2023-01-12 23:30 UTC, bucherarnold approved these changes

2023-01-13 08:45 UTC, merged